services:
  - type: web
    name: sp105-aiml-explainer
    runtime: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: python src/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10